### ISSUE TITLE
Which OS did you use in that screenshot?

### ISSUE THREAD

**Issue by lucasgdo** [Trollwut/Dracula-by-Trollwut#1]
Along with DE, WM and theme if possible :)

**Comment by Trollwut** [comment]
hey @lucasgdo :)

I *think* this was back when I had Arch Linux running. Nowadays I use Manjaro on every system. The WM is still i3 (no DE). The top and bottom bar in the scrot are polybar

Unfortunately I don't have dotfiles anymore for this setup

**Comment by lucasgdo** [comment]
Thank you very much, awesome theme! Arch rules

**Comment by Trollwut** [comment]
thanks mate! :)

I'm gonna close this issue, as this is being answered. If you have another question about the screenshot setup, feel free to reopen!
